### ISSUE TITLE
Include this kind of feature directly in node

### ISSUE THREAD

**Issue by rom1504** [yortus/require-self#16]
I feel the feature of this module is something that is missing from node.js itself.
Do you have any idea if there is any open issue to solve that situation directly in node so this module is not needed ?

**Comment by yortus** [comment]
Good question. I highly doubt node.js would change its [CommonJS module system](https://nodejs.org/dist/latest-v12.x/docs/api/modules.html#modules_modules) now, since it's marked stable and things are moving towards [ESM](https://nodejs.org/dist/latest-v12.x/docs/api/esm.html#esm_ecmascript_modules) anyway.

Something like [Import Maps](https://github.com/WICG/import-maps) would resolve this. Or for node.js specifically, a `package.json` [`"imports"` field](https://github.com/jkrems/proposal-pkg-exports#3-imports-field).

In any case, there's nothing actionable here for this project, so closing.
